name: fuzzing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: fuzzing test
        run: | 
          cd Week2/ProjectX2-main
          docker build . --file Dockerfile --tag projectx2
          docker run projectx2